import { logger } from "../utils/logger";
import { Copilot } from "../utils/copilot";
import { FileManager } from "../utils/file-manager";
import path from "path";

export interface ScenarioData {
  url: string;
  scenarios: string[];
  actionKeywords?: string[];
}

export class CopilotGeneratorAgent {
  static async generate(data: ScenarioData): Promise<string> {
    logger.info("Copilot Generator Agent is running...");
    logger.info(`Generating tests for: ${data.url}`);

    const scenarioText = data.scenarios.join(", ");
    const keywordsText = data.actionKeywords?.join(", ") || "verify, check, validate";

    const prompt = `Generate a production-ready Playwright TypeScript test script with these requirements:

Target URL: ${data.url}
Test Scenarios: ${scenarioText}
Action Keywords: ${keywordsText}

Requirements:
1. Use @playwright/test framework
2. Include proper imports and test setup
3. Add page.goto("${data.url}") at the start
4. Create meaningful test cases for each scenario
5. Use generic selectors (body, main, [role], text content) - avoid brittle selectors
6. Add proper assertions (URL check, page visibility, element presence)
7. Handle dynamic websites gracefully
8. Include error messages in assertions
9. Add timeouts where needed
10. Make tests independent and reusable

Output ONLY valid TypeScript code. No explanations, no markdown, no comments.`;

    try {
      logger.info("Calling GitHub Copilot CLI for code generation...");
      
      // Call Copilot CLI for code generation
      const generatedCode = await Copilot.ask(prompt);

      if (!generatedCode || generatedCode.trim().length === 0) {
        throw new Error("Copilot returned empty code");
      }

      // Validate generated code
      this.validateGeneratedCode(generatedCode);

      // Save to file
      const filePath = path.join("tests", "generated", "auth.spec.ts");
      logger.info(`Writing generated script to: ${filePath}`);

      FileManager.write(filePath, generatedCode);
      logger.success(`✓ Playwright test script generated by Copilot CLI (${generatedCode.length} chars)`);
      logger.success(`✓ Saved to ${filePath}`);

      return filePath;
    } catch (error) {
      logger.error(`Copilot Generator Agent failed: ${error}`);
      throw error;
    }
  }

  private static validateGeneratedCode(code: string): void {
    logger.info("Validating generated code...");

    const checks = [
      { pattern: /import\s+{.*}/s, name: "imports" },
      { pattern: /test\(/s, name: "test cases" },
      { pattern: /page\.goto/s, name: "navigation" },
      { pattern: /expect\(/s, name: "assertions" },
    ];

    const results = checks.map(check => ({
      name: check.name,
      passed: check.pattern.test(code)
    }));

    const allPassed = results.every(r => r.passed);
    
    results.forEach(result => {
      if (result.passed) {
        logger.info(`  ✓ ${result.name}`);
      } else {
        logger.warn(`  ⚠ ${result.name}`);
      }
    });

    if (!allPassed) {
      logger.warn("⚠ Some validations failed - code may need adjustment");
    } else {
      logger.success("✓ All validations passed");
    }
  }
}
