import { logger } from "../utils/logger";
import { AIConfig } from "../utils/ai-config";
import { FileManager } from "../utils/file-manager";
import { DOMSnapshot } from "./dom-types";
import { ScenarioResult } from "./scenario-agent";
import path from "path";

export class AIGeneratorAgent {
  static async generate(data: ScenarioResult): Promise<string> {
    logger.info("AI Generator Agent is running...");
    logger.info(`Generating tests for: ${data.url}`);
    logger.info(`Scenarios: ${data.scenarios.join(", ")}`);
    
    if (data.domSnapshot) {
      logger.info(`Using DOM snapshot with ${data.domSnapshot.elements.length} extracted elements`);
    }

    const scenarioText = data.scenarios.join(", ");
    const keywordsText = data.actionKeywords?.join(", ") || "verify, check, validate";

    // Include DOM element information if available
    const domContext = data.domSnapshot
      ? `\n\nExtracted Page Elements:
${this.formatDOMForPrompt(data.domSnapshot)}`
      : "";

    const prompt = `Generate a production-ready Playwright TypeScript test script with these requirements:

Target URL: ${data.url}
Test Scenarios: ${scenarioText}
Action Keywords: ${keywordsText}${domContext}

Requirements:
1. Use @playwright/test framework
2. Include proper imports and test setup
3. Add page.goto("${data.url}") at the start of each test
4. Create one test per scenario
5. Use the extracted elements and selectors provided above when available
6. Use generic, stable selectors (role-based, text content) - avoid brittle CSS selectors
7. Add proper assertions (URL check, element visibility, content validation)
8. Use waitForLoadState("domcontentloaded") by default.
9. Avoid networkidle unless explicitly required.
10. Include descriptive error messages in assertions
11. Add appropriate timeouts (30-60 seconds for page loads)
12. Make tests independent and reusable
13. Use async/await properly
14. Return ONLY valid TypeScript code. No markdown, no comments, no explanations.`;

    try {
      logger.info("Calling AI provider for code generation...");
      const provider = AIConfig.getGeneratorProvider();
      
      const response = await provider.generate(prompt);

      if (!response.success || !response.data) {
        throw new Error(`Generator failed: ${response.error}`);
      }

      const generatedCode = response.data.trim();

      if (generatedCode.length === 0) {
        throw new Error("AI provider returned empty code");
      }

      // Validate generated code
      this.validateGeneratedCode(generatedCode);

      // Save to file
      const filePath = path.join("tests", "generated", "auth.spec.ts");
      logger.info(`Writing generated script to: ${filePath}`);

      FileManager.write(filePath, generatedCode);
      logger.success(`✓ Playwright test script generated by ${response.provider}`);
      logger.success(`✓ Saved to ${filePath} (${generatedCode.length} chars)`);

      return filePath;
    } catch (error) {
      logger.error(`AI Generator Agent failed: ${error}`);
      throw error;
    }
  }

  /**
   * Format DOM snapshot for inclusion in AI prompt
   */
  private static formatDOMForPrompt(snapshot: DOMSnapshot): string {
    const topButtons = snapshot.elements
      .filter((e) => e.type === "button")
      .slice(0, 5);
    const topLinks = snapshot.elements
      .filter((e) => e.type === "link")
      .slice(0, 5);
    const topInputs = snapshot.elements
      .filter((e) => e.type === "input")
      .slice(0, 3);

    let format = `\nPage Statistics:
- Total Elements: ${snapshot.totalElements}
- Buttons: ${snapshot.statistics.buttons}
- Links: ${snapshot.statistics.links}
- Inputs: ${snapshot.statistics.inputs}
- Interactive Elements: ${snapshot.statistics.interactiveElements}

Key Elements (use these selectors in tests):
`;

    if (topButtons.length > 0) {
      format += `\nButtons:
${topButtons.map((b) => `- "${b.text}" [selector: ${b.selector}]`).join("\n")}`;
    }

    if (topInputs.length > 0) {
      format += `\n\nInputs:
${topInputs.map((i) => `- ${i.tagName} [selector: ${i.selector}]${i.placeholder ? ` placeholder: "${i.placeholder}"` : ""}`).join("\n")}`;
    }

    if (topLinks.length > 0) {
      format += `\n\nLinks:
${topLinks.map((l) => `- "${l.text}" [selector: ${l.selector}]`).join("\n")}`;
    }

    return format;
  }
  private static validateGeneratedCode(code: string): void {
    logger.info("Validating generated code structure...");

    const checks = [
      { pattern: /import\s+{.*test/s, name: "imports" },
      { pattern: /test\s*\(/s, name: "test cases" },
      { pattern: /page\.goto/s, name: "navigation" },
      { pattern: /expect\s*\(/s, name: "assertions" },
    ];

    const results = checks.map(check => ({
      name: check.name,
      passed: check.pattern.test(code)
    }));

    const allPassed = results.every(r => r.passed);
    
    results.forEach(result => {
      if (result.passed) {
        logger.info(`  ✓ ${result.name}`);
      } else {
        logger.warn(`  ⚠ ${result.name}`);
      }
    });

    if (!allPassed) {
      logger.warn("⚠ Some validations failed - code may need regeneration");
    } else {
      logger.success("✓ All validations passed");
    }
  }
}

